### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by zshwei** [arve0/nodepdf-series#6]
Firstly, I like this package very much! Thanks. It worked well for English html pages. Could you pls make it a little more international? For example support Chinese characters.  Or any guide I can make it support Chinese?

Thanks.

**Comment by arve0** [comment]
This package relies on phantomjs, which is [discontinued](https://github.com/ariya/phantomjs/issues/15344). You might have better luck with [puppeteer](https://github.com/GoogleChrome/puppeteer). The [usage section](https://github.com/GoogleChrome/puppeteer#usage) in the readme has an example of generating PDFs.
